/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
        
package sensores02;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.awt.Color;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
/**
 *
 * @author jdemc
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }
    Stack pila = new Stack();
    PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
    SerialPortEventListener listener = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            try {
                System.out.println(ino.receiveData());
            } catch (ArduinoException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Btn_Enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_OutputTempSerial = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt_InputCadena = new javax.swing.JTextPane();
        Btn_Conectar = new javax.swing.JButton();
        Btn_Desconectar = new javax.swing.JButton();
        Btn_Convertir = new javax.swing.JButton();
        Txt_OutputTempA = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txt_OutputBinario = new javax.swing.JTextArea();
        Btn_VentiladorStatus = new javax.swing.JToggleButton();
        Btn_11 = new javax.swing.JToggleButton();
        Btn_12 = new javax.swing.JToggleButton();
        Btn_13 = new javax.swing.JToggleButton();
        Btn_14 = new javax.swing.JToggleButton();
        Btn_17 = new javax.swing.JToggleButton();
        Btn_15 = new javax.swing.JToggleButton();
        Btn_16 = new javax.swing.JToggleButton();
        Btn_21 = new javax.swing.JToggleButton();
        Btn_22 = new javax.swing.JToggleButton();
        Btn_23 = new javax.swing.JToggleButton();
        Btn_24 = new javax.swing.JToggleButton();
        Btn_25 = new javax.swing.JToggleButton();
        Btn_26 = new javax.swing.JToggleButton();
        Btn_27 = new javax.swing.JToggleButton();
        Btn_31 = new javax.swing.JToggleButton();
        Btn_32 = new javax.swing.JToggleButton();
        Btn_33 = new javax.swing.JToggleButton();
        Btn_34 = new javax.swing.JToggleButton();
        Btn_35 = new javax.swing.JToggleButton();
        Btn_36 = new javax.swing.JToggleButton();
        Btn_37 = new javax.swing.JToggleButton();
        Btn_41 = new javax.swing.JToggleButton();
        Btn_42 = new javax.swing.JToggleButton();
        Btn_43 = new javax.swing.JToggleButton();
        Btn_44 = new javax.swing.JToggleButton();
        Btn_45 = new javax.swing.JToggleButton();
        Btn_46 = new javax.swing.JToggleButton();
        Btn_47 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt_OutputProximidad = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Txt_OutputHumedad = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Txt_Estado = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Txt_OutputBinario1 = new javax.swing.JTextArea();

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadena");

        Btn_Enviar.setText("Enviar");
        Btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarActionPerformed(evt);
            }
        });

        Txt_OutputTempSerial.setColumns(20);
        Txt_OutputTempSerial.setRows(5);
        jScrollPane1.setViewportView(Txt_OutputTempSerial);

        jScrollPane2.setViewportView(Txt_InputCadena);

        Btn_Conectar.setText("Conectar");
        Btn_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConectarActionPerformed(evt);
            }
        });

        Btn_Desconectar.setText("Desconectar");
        Btn_Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DesconectarActionPerformed(evt);
            }
        });

        Btn_Convertir.setText("Convertir");
        Btn_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConvertirActionPerformed(evt);
            }
        });

        Txt_OutputBinario.setColumns(20);
        Txt_OutputBinario.setRows(5);
        jScrollPane4.setViewportView(Txt_OutputBinario);

        Btn_VentiladorStatus.setLabel("Ventilador");

        Btn_11.setLabel("1");
        Btn_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_11ActionPerformed(evt);
            }
        });

        Btn_12.setLabel("2");
        Btn_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_12ActionPerformed(evt);
            }
        });

        Btn_13.setText("3");
        Btn_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_13ActionPerformed(evt);
            }
        });

        Btn_14.setText("4");
        Btn_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_14ActionPerformed(evt);
            }
        });

        Btn_17.setText("7");
        Btn_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_17ActionPerformed(evt);
            }
        });

        Btn_15.setText("5");
        Btn_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_15ActionPerformed(evt);
            }
        });

        Btn_16.setText("6");
        Btn_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_16ActionPerformed(evt);
            }
        });

        Btn_21.setText("1");
        Btn_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_21ActionPerformed(evt);
            }
        });

        Btn_22.setText("2");
        Btn_22.setToolTipText("");
        Btn_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_22ActionPerformed(evt);
            }
        });

        Btn_23.setText("3");
        Btn_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_23ActionPerformed(evt);
            }
        });

        Btn_24.setText("4");
        Btn_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_24ActionPerformed(evt);
            }
        });

        Btn_25.setText("5");
        Btn_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_25ActionPerformed(evt);
            }
        });

        Btn_26.setText("6");
        Btn_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_26ActionPerformed(evt);
            }
        });

        Btn_27.setText("7");
        Btn_27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_27ActionPerformed(evt);
            }
        });

        Btn_31.setText("1");
        Btn_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_31ActionPerformed(evt);
            }
        });

        Btn_32.setText("2");
        Btn_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_32ActionPerformed(evt);
            }
        });

        Btn_33.setText("3");
        Btn_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_33ActionPerformed(evt);
            }
        });

        Btn_34.setText("4");
        Btn_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_34ActionPerformed(evt);
            }
        });

        Btn_35.setText("5");
        Btn_35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_35ActionPerformed(evt);
            }
        });

        Btn_36.setText("6");
        Btn_36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_36ActionPerformed(evt);
            }
        });

        Btn_37.setText("7");
        Btn_37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_37ActionPerformed(evt);
            }
        });

        Btn_41.setText("1");
        Btn_41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_41ActionPerformed(evt);
            }
        });

        Btn_42.setText("2");
        Btn_42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_42ActionPerformed(evt);
            }
        });

        Btn_43.setText("3");
        Btn_43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_43ActionPerformed(evt);
            }
        });

        Btn_44.setText("4");
        Btn_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_44ActionPerformed(evt);
            }
        });

        Btn_45.setText("5");
        Btn_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_45ActionPerformed(evt);
            }
        });

        Btn_46.setText("6");
        Btn_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_46ActionPerformed(evt);
            }
        });

        Btn_47.setText("7");
        Btn_47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_47ActionPerformed(evt);
            }
        });

        jLabel2.setText("Humedad");

        Txt_OutputProximidad.setColumns(20);
        Txt_OutputProximidad.setRows(5);
        jScrollPane5.setViewportView(Txt_OutputProximidad);

        jLabel3.setText("Proximidad");

        Txt_OutputHumedad.setColumns(20);
        Txt_OutputHumedad.setRows(5);
        jScrollPane6.setViewportView(Txt_OutputHumedad);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        jLabel4.setText("Humo");

        Txt_Estado.setText("OK");

        Txt_OutputBinario1.setColumns(20);
        Txt_OutputBinario1.setRows(5);
        jScrollPane8.setViewportView(Txt_OutputBinario1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Txt_OutputTempA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(Btn_VentiladorStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Btn_Convertir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Btn_Enviar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Btn_Desconectar)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Conectar)))
                    .addComponent(Txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_41, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_42, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_43, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_44, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_45, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_46, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_47, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(Btn_17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_37, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Convertir)
                    .addComponent(Btn_Enviar)
                    .addComponent(Btn_Desconectar)
                    .addComponent(Btn_Conectar)
                    .addComponent(Btn_11)
                    .addComponent(Btn_12)
                    .addComponent(Btn_13)
                    .addComponent(Btn_14)
                    .addComponent(Btn_15)
                    .addComponent(Btn_17)
                    .addComponent(Btn_16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_OutputTempA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_VentiladorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_21)
                            .addComponent(Btn_22)
                            .addComponent(Btn_23)
                            .addComponent(Btn_24)
                            .addComponent(Btn_25)
                            .addComponent(Btn_26)
                            .addComponent(Btn_27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_31)
                            .addComponent(Btn_32)
                            .addComponent(Btn_33)
                            .addComponent(Btn_34)
                            .addComponent(Btn_35)
                            .addComponent(Btn_36)
                            .addComponent(Btn_37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_41)
                            .addComponent(Btn_42)
                            .addComponent(Btn_43)
                            .addComponent(Btn_44)
                            .addComponent(Btn_45)
                            .addComponent(Btn_46)
                            .addComponent(Btn_47))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jScrollPane7))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Cadena.");
        Btn_VentiladorStatus.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EnviarActionPerformed

    private void Btn_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConectarActionPerformed
        try {
            ino.arduinoRX("COM3",9600, listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_ConectarActionPerformed

    private void Btn_DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DesconectarActionPerformed

    private void Btn_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConvertirActionPerformed
        // TODO add your handling code here:
       String s = Txt_InputCadena.getText();
		StringBuilder buf = new StringBuilder();
		for (int i = 0; i < s.length(); i++ ) {
		    int characterASCII = s.charAt(i);
		    //System.out.println(Integer.toBinaryString(characterASCII));
		    buf.append(Integer.toBinaryString(characterASCII)+"\n");
		}
		String cadena = buf.toString();
                Txt_OutputBinario.setText(cadena+"");
                
		for (int j = 0; j < 32; j++ ) {
                    if (cadena.charAt(j) != '\n'){
                        pila.push(cadena.charAt(j));
                    }
		}
    
//                System.out.print(pila);
                
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_47.setBackground(Color.red);
                    }  
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_46.setBackground(Color.red);
                    }
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_45.setBackground(Color.red);
                    }
                }
               
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_44.setBackground(Color.red);
                    }
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_43.setBackground(Color.red);
                    }
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_42.setBackground(Color.red);
                    }
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_41.setBackground(Color.red);
                    }
                    
                }
                if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_37.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_36.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_35.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_34.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_33.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_32.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_31.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_27.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_26.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_25.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_24.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_23.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_22.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_21.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_17.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_16.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_15.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_14.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_13.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_12.setBackground(Color.red);
                    }
                }if(!pila.empty()){
                    if(pila.pop().equals('1')){
                        Btn_11.setBackground(Color.red);
                    }
                }
//                System.out.print(pila);
    }//GEN-LAST:event_Btn_ConvertirActionPerformed

    private void Btn_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_11ActionPerformed

    private void Btn_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_12ActionPerformed

    private void Btn_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_13ActionPerformed

    private void Btn_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_14ActionPerformed

    private void Btn_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_17ActionPerformed

    private void Btn_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_15ActionPerformed

    private void Btn_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_16ActionPerformed

    private void Btn_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_21ActionPerformed

    private void Btn_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_22ActionPerformed

    private void Btn_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_23ActionPerformed

    private void Btn_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_24ActionPerformed

    private void Btn_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_25ActionPerformed

    private void Btn_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_26ActionPerformed

    private void Btn_27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_27ActionPerformed

    private void Btn_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_31ActionPerformed

    private void Btn_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_32ActionPerformed

    private void Btn_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_33ActionPerformed

    private void Btn_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_34ActionPerformed

    private void Btn_35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_35ActionPerformed

    private void Btn_36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_36ActionPerformed

    private void Btn_37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_37ActionPerformed

    private void Btn_41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_41ActionPerformed

    private void Btn_42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_42ActionPerformed

    private void Btn_43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_43ActionPerformed

    private void Btn_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_44ActionPerformed

    private void Btn_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_45ActionPerformed

    private void Btn_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_46ActionPerformed

    private void Btn_47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_47ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_11;
    private javax.swing.JToggleButton Btn_12;
    private javax.swing.JToggleButton Btn_13;
    private javax.swing.JToggleButton Btn_14;
    private javax.swing.JToggleButton Btn_15;
    private javax.swing.JToggleButton Btn_16;
    private javax.swing.JToggleButton Btn_17;
    private javax.swing.JToggleButton Btn_21;
    private javax.swing.JToggleButton Btn_22;
    private javax.swing.JToggleButton Btn_23;
    private javax.swing.JToggleButton Btn_24;
    private javax.swing.JToggleButton Btn_25;
    private javax.swing.JToggleButton Btn_26;
    private javax.swing.JToggleButton Btn_27;
    private javax.swing.JToggleButton Btn_31;
    private javax.swing.JToggleButton Btn_32;
    private javax.swing.JToggleButton Btn_33;
    private javax.swing.JToggleButton Btn_34;
    private javax.swing.JToggleButton Btn_35;
    private javax.swing.JToggleButton Btn_36;
    private javax.swing.JToggleButton Btn_37;
    private javax.swing.JToggleButton Btn_41;
    private javax.swing.JToggleButton Btn_42;
    private javax.swing.JToggleButton Btn_43;
    private javax.swing.JToggleButton Btn_44;
    private javax.swing.JToggleButton Btn_45;
    private javax.swing.JToggleButton Btn_46;
    private javax.swing.JToggleButton Btn_47;
    private javax.swing.JButton Btn_Conectar;
    private javax.swing.JButton Btn_Convertir;
    private javax.swing.JButton Btn_Desconectar;
    private javax.swing.JButton Btn_Enviar;
    private javax.swing.JToggleButton Btn_VentiladorStatus;
    private javax.swing.JLabel Txt_Estado;
    private javax.swing.JTextPane Txt_InputCadena;
    private javax.swing.JTextArea Txt_OutputBinario;
    private javax.swing.JTextArea Txt_OutputBinario1;
    private javax.swing.JTextArea Txt_OutputHumedad;
    private javax.swing.JTextArea Txt_OutputProximidad;
    private javax.swing.JLabel Txt_OutputTempA;
    private javax.swing.JTextArea Txt_OutputTempSerial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
